#!/bin/sh
#
# Start baresip-lvgl
#

case "$1" in
  start)
	echo "Starting baresip-lvgl..."
	# Ensure audio/video devices are ready
	/usr/bin/baresip-lvgl > /var/log/baresip.log 2>&1 &
	;;
  stop)
	echo "Stopping baresip-lvgl..."
	killall baresip-lvgl
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
